astrocut/_astropy_init.py
This one-line change prevents pytest from picking up the test function as a test. See astropy/package-template#373.
*This is an automated fix by @pllim. If this is opened in error, please close without merge.*
=> Prevent pytest from picking up test function as a test

astrocut/cube_cut.py, astrocut/tests/test_cube_cut.py
Thank you for providing the fabulous TESScut service.  It is impressively fast and user-friendly!
I noticed that the files returned by TESScut contain an aperture mask image extension (HDU 2) which contains floating point values.  In contrast, the standard TESS/Kepler target pixel files contain integers in this extension.
This is a minor issue because this extension represents a bitmask image, and therefore *lightkurve* (and likely other data analysis tools) expect to encounter integers here. I believe this PR fixes the issue!
=> Bugfix: the aperture extension must use integers

astrocut/cube_cut.py, astrocut/make_cube.py
Currently the TESScut service returns Target Pixel Files with a header which suggests that they were created using the FFI exporter of the official pipeline, cf.:
```
CREATOR = '113 FfiExporter'    / pipeline job and program used to produce this f
PROCVER = 'spoc-3.3.31-20180902' / SW version 
```
This PR proposes to set the `CREATOR` keyword to contain `astrocut`, which enables TPFs generated using astrocut/tesscut to be identified more easily.
Again, thank you for providing the fantastic TESScut service!
=> Set the `CREATOR` keyword to `astrocut`

astrocut/cube_cut.py
In `cube_cut`, the string formatting for target coordinates in the downloaded filename was not specified. The minor change in this PR ensure that TESScut filenames are saved with the coordinates in the form of floats with consistent length. This makes it easier to check locally if a given target has already been downloaded.
=> Uniform formatting on target pixel file names

CHANGES.rst, astrocut/cube_cut.py, astrocut/make_cube.py
Sometimes the TESS pipeline fails to produce a WCS object, in this case the FFI lacks the WCS header keywords.  This is a problem for Astrocut in two situations:
1. The FFI used to set up the header keywords table in the cube file is missing the WCS header keywords, in which case the cube as a whole is missing those keywords.
2. The FFI used to make the WCS information for the cutout lacks the WCS keywords.  In this case a WCS object cannot be created so the cutout cannot proceed.
This PR solve both of these problems with the following changes:
- In the make_cube file the WCS keyword "CTYPE1" is checked and must be present for an FFI to be used as the template for making the header table.
- In the cube_cut file the WCS keyword "CTYPE1" is checked and must be present  for the row of header …
=> WCS bugfix

CHANGES.rst, astrocut/cutouts.py, astrocut/tests/test_cutouts.py, docs/astrocut/index.rst
Two minor improvements that I wanted to get in before adding the image option to the zCut service:
- Changed the `minmax_cut` argument to `minmax_value` for clarity.
- Improved the output file names so they no longer include spaces, and remain readable when the cutout size is given with units.
=> Minor improvements

.travis.yml, CHANGES.rst, astrocut/cube_cut.py, astrocut/cutouts.py, astrocut/exceptions.py, docs/astrocut/index.rst
Adding error handling so that if one file in a list for fits_cut or image_cut raises an error, the user still gets a cutout with the rest of the files.  A warning is raised showing which files caused a problem and what the error was.
=> Error handling

CHANGES.rst, astrocut/cube_cut.py, astrocut/utils/wcs_fitting.py
The PR resolves issue https://github.com/spacetelescope/astrocut/issues/22.
- Updated the local `fit_wcs_from_points` to match what is in Astropy.
- Added additional residual checking.
- Opened bugfix PR to add the same residual checking in Astropy (https://github.com/astropy/astropy/pull/10155).
- Added check so that for Astropy version >=4.0.1 the Astropy function will be used preferentially (this will be the version my bugfix goes into)
=> Updating wcs fitting to match astropy

.travis.yml, CHANGES.rst, astrocut/cube_cut.py, astrocut/tests/test_cube_cut.py, astrocut/utils/wcs_fitting.py, docs/astrocut/index.rst
This pertains to TESS cutouts.
Currently when fitting a linear WCS to a cutout we use every single pixel in the fit. This gets inefficient for large cutouts and does not make the fit appreciable better.
This PR limits the number of pixels used to a maximum of 100, spread evenly throughout the cutout.
=> Streamline WCS fitting

CHANGES.rst, astrocut/cutouts.py
Older drizzle files (e.g. CANDELS) have SIP distortion keywords in their headers even though the drizzle process removes the need for them.  This causes problems when loading and using the associated WCS information. The current solution is to offer an option to drop all keywords after the first instance of a specific keyword.  This not optimal. 
This PR handles that issue by catching the warning that astropy issues when it finds inconstant WCS keywords, assumes that the CTYPE keywords are correct and drops all SIP coefficients in this case. Consequently the `drop_after` keyword is deprecated.
=> Replace drop_after argument

CHANGES.rst, astrocut/cube_cut.py, astrocut/cutouts.py, astrocut/make_cube.py
This PR changes the memmap mode when reading a fits file from `readonly` to `denywrite,` the difference is that `readonly` map to memmap access mode "ACCESS_COPY" while `denywrite` maps to "ACCESS_READ." For our purposes the issue with "ACCESS_COPY" is that it requires more memory, which can cause problems for larger files.
=> Changing memmap mode

astrocut/make_cube.py, docs/astrocut/index.rst, docs/astrocut/install.rst
In PR https://github.com/spacetelescope/astrocut/pull/35 I forgot to update the documentation to reflect the new functionality. This PR does that.
=> Updating docs for iterative cubing

astrocut/cutout_processing.py
Updating the internal tstart/stop values to match what actually appears in the cutout table, and also adding them to the default filename to make it more unique.
=> Path cutout tstart/stop values

astrocut/_astropy_init.py
This is probably leftover from package template. This package does not use the `astropy` configuration system at all.
Also see astropy/astropy#11497
=> MNT: Remove unused astropy config code

astrocut/cutouts.py, astrocut/tests/test_cutouts.py
It turns out removing sip keywords manually is not necessary, you can just set `wcs.sip = 0`
=> Minor wcs update

.github/workflows/ci_workflows.yml, setup.cfg, tox.ini
Fixing deprecated scripts that are causing CI tests to break. Changes include:
Tests are passing except for the allowed failure for python 3.7, so I will mark this PR as ready for review. Thanks in advance!
=> fixing broken tests from GitHub Actions CI run

astrocut/cutout_processing.py, astrocut/tests/test_cutout_processing.py
Fixing an error originating from having forward slashes and spaces in the target name (e.g. `C/2014 UN271`). This edit catches any `/` or spaces in the name of the target and replaces them accordingly, which allows the script to continue writing the output Target Pixel File. 
This closes https://github.com/spacetelescope/astrocut/issues/50
=> fixing error resulting from forward slash in target name

.github/workflows/ci_workflows.yml, astrocut/__init__.py, astrocut/make_cube.py, astrocut/tests/test_make_cube.py, astrocut/tests/utils_for_test.py, tox.ini
Implements a class based off the existing `CubeFactory` class that can generate cubes out of TICA FFIs. 
Note: This is one of the core four projects for MAST Q3 and must be implemented before June 30. 
self.info_table[kwd][i] = ffi_data[0].header.get(kwd, nulval)`
UPDATE: After investigating TruncatedString warning, I found the source of the issue being under `_build_info_table` where the default length of a string keyword value is set based on the length of the string keyword value in the designated `template_file` . In the event that the string kwd value in one FFI is longer than the string kwd value in the template file, a stringTruncated Warning will pop up. I fixed the default value and compared the generated `info_table` with the `info_table` before fixing, and it doesn't seem to …
=> Make cubes out of TICA FFIs

astrocut/make_cube.py
In `TICACubeFactory`: Adding the `max_memory` argument to `update_cube` to make things consistent with `make_cube`
The `max_memory` argument determines the amt of memory that should be allocated for processing each FFI added to the cube. It will determine the size of the "chunk" of the FFI to process at a time. 
Imports auto-sorted with `isort`
=> max_memory arg added to update_cube

astrocut/cube_cut.py, astrocut/tests/test_cube_cut.py
`_parse_table_info` was calling for a keyword in the cube that does not exist until after the cutout file is made. Updated this WCS validation check accordingly, to work with a header keyword that SPOC and TICA both have, and is always the same value, and implies that other relevant WCS info is also in the header of the FFI. 
Import restructuring from VSCode's `isort`
=> hotfix for `cube_cut` checking for valid WCS info

astrocut/make_cube.py, astrocut/tests/test_make_cube.py, setup.cfg, tox.ini
Currently the errors that get returned when SPOC FFIs are fed into `TicaCubeFactory` and vice versa are vague and not helpful to the user. This PR updates the error handling by raising an error when the wrong type of FFI is fed into either `CubeFactory` or `TicaCubeFactory` to make TESS cubes.
----
----
The following two screenshots show the error that gets thrown when feeding the wrong type of FFI to `CubeFactory` and `TicaCubeFactory`:
=> Error handling for `CubeFactory` and `TicaCubeFactory`

astrocut/cube_cut.py, astrocut/tests/test_cube_cut.py
adds `threads` to the CutoutFactory.__init__() method which controls whether the threadpool is used.
Using this benchmark code:
```python
"""Benchmark threading performance"""
import warnings
from tempfile import TemporaryDirectory
from astropy.coordinates import SkyCoord
from astropy.io.fits.verify import VerifyWarning
from astrocut.cube_cut import CutoutFactory
warnings.filterwarnings("ignore", category=VerifyWarning)
coord = SkyCoord(217.42893801, -62.67949189, unit="deg", frame="icrs")
cube_file = "s3://stpubdata/tess/public/mast/tess-s0038-2-2-cube.fits"
tmp_path = TemporaryDirectory()
def cutout(threads=None):
cutout_file = CutoutFactory(threads=threads).cube_cut(cube_file, coord, 31, output_path=str(tmp_path))
return cutout_file
if __name__ == "__main__":
import timeit
bmark_val = …
```
=> cutout in threadpool

astrocut/make_cube.py, astrocut/tests/test_make_cube.py
Addressing ticket ASB-22318. Created a test cube using 500 FFIs from TICA Sector 67, cam1-ccd1. Created cube has expected dimensions, see output from `fitsinfo` below. Cube created without error array is ~1/2 the size of a cube created with the error array (8.68 vs 17.35 GB).
```
Filename: /home/halewis/hlsp/tica/tica_cubes/s0067/tica-s0067-1-1-cube.fits
No.    Name      Ver    Type      Cards   Dimensions   Format
0  PRIMARY       1 PrimaryHDU     198   ()      
1                1 ImageHDU         9   (1, 500, 2136, 2078)   float32   
2                1 BinTableHDU    598   500R x 198C   [D, J, J, J, J, D, J, J, 2A, D, D, D, D, D, D, D, D, D, D, D, D, J, J, J, J, J, J, J, D, J, D, D, D, D, D, D, D, D, 3A, J, J, 16A, D, D, D, D, 9A, 5A, D, 15A, 4A, 4A, D, D, D, D, D, D, D, D, 12A, 12A, D, …
```
=> removing error array dimension from TicaCubeFactory

astrocut/cube_cut.py, astrocut/cutouts.py, astrocut/make_cube.py, astrocut/tests/test_cube_cut.py
This PR updates `CutoutFactory` to account for the removed error array in `TicaCubeFactory` (work that was done in  #87). It involves turning the `product` kwarg from `cube_cut()` into a class attribute so that it doesn't have to be fed into every method as an argument before being called. It also involves using this new `self.product` class attribute to make conditionals that make the code dynamic and changes the logic depending on whether the product for the cutouts is `"TICA"` or `"SPOC"`. Unit test changes are also made where appropriate.
----
----
=> Adapting `CutoutFactory` to account for error-less TICA Cubes

.readthedocs.yml, astrocut/__init__.py, setup.cfg
The Astrocut RTD maintainers received an e-mail notification about adding a `.readthedocs.yml` v2 configuration file to our project, as they will no longer be supporting projects with implicit dependencies. More info can be found in this article: https://blog.readthedocs.com/migrate-configuration-v2/ . 
@ceb8 already built us a `.readthedocs.yml` v2 file, so we are good to go. The reason we actually got that e-mail was because we had the following checkbox checked off in the `Advanced Settings` of the `Astrocut` project, which is the feature that will be deprecated in September 2023:
All it needed was to be updated to require python 3.8 instead of 3.7, because 3.7 does not jive with `astropy>=5.2`, which caused our documentation to break for the past 4 months, and is the actual reason for …
=> Updating `.readthedocs.yml` with Python3.8

astrocut/tests/test_cube_cut.py
Updates to existing unit tests and adding new tests to account for changes in `CutoutFactory` (made in #88). Tests verify that cutouts are being made correctly from the new TICA cubes (without error arrays) and verify known differences in TICA vs. SPOC FFIs, cubes, and cutouts.
Note, there is a placeholder unittest (`test_cube_cut.py::test_tica_cutout_error`) to remind us to go back to look at whether we can/should point the test to an existing TICA cube (one that *does* have the error array and will be among the last cubes to me re-built, e.g., Sector 27) that will be re-built later, to verify that cutouts can still be made from cubes with error array.
=> Update cube and cutout unittests

docs/astrocut/file_formats.rst, docs/astrocut/index.rst
Update docs to reflect changes in TICA cube format
=> Update docs to reflect changes in TICA cube format

.github/workflows/pypi-package.yml, README.rst, setup.py
Created a GitHub workflow to build wheels, test package, and publish package to the official PyPI, all triggered by the creation and push of a new tag on @spacetelescope/astrocut.
=> Use GitHub Actions for publishing new releases to PyPI

.github/workflows/ci_workflows.yml, astrocut/__init__.py, setup.cfg
asdf dependencies don't allow 3.8 (see PR: https://github.com/spacetelescope/astrocut/pull/105)
we can drop 3.8 (and probably should, since astropy has also dropped 3.8 for newer releases)
=> drop python 3.8 support

astrocut/asdf_cutouts.py, astrocut/tests/test_asdf_cut.py, setup.cfg
The Roman Space Telescope will have its data stored in a new file format called [ASDF](https://asdf.readthedocs.io/en/latest/). In order to continue supporting our userbase and enabling productive science, the `astrocut` tool needs to be expanded to allow for the creation of cutouts of Roman mission products.
=> New Feature: ASDF Cutout Functionality

astrocut/asdf_cutouts.py, astrocut/tests/test_asdf_cut.py
This PR fixes a bug in the asdf cutout code when the input data to the cutout was an Astropy Quantity instead of a straight numpy array.  Now it accepts both and converts to a data array when writing out to the fits file. 
It also now allows for the return of the cutout object for inspection.
=> Bug fix for asdf cutouts with data as astropy quantity

astrocut/asdf_cutouts.py, astrocut/tests/test_asdf_cut.py
This PR switches the coordinate to pixel conversion to `gwcs`.  It switches the cutout to mode to `partial` which preserves the original cutout shape when requesting a cutout with partial area outside the image bounds.   It wraps the cutout command in try-except when the requested cutout is completely outside the original image.   It adds tests for making cutouts around poles.
=> Updates to asdf cutout for edge cases

astrocut/asdf_cutouts.py, astrocut/tests/test_asdf_cut.py
This PR adds the option to output the cutout as an asdf file, instead of a fits file.   The asdf cutout file is a minimal tree structure, mirroring the format of the original roman image, i.e.
```
asdf tree:
- "roman":
- "meta":
- "wcs" - the gwcs of the cutout 
- "data" - the cutout data
```
The included wcs is a sliced gwcs object from the original input to the cutout shape.  This option was chosen to try to preserve as much as possible the original image transformations.  It's a bit of a hack as there's no built-in way of slicing a gwcs yet, nor does `astropy.Cutout2D` support gwcs input yet.    
It also adds a test for the RA=0 edge case.
=> Adds option for cutout output to asdf file

astrocut/asdf_cutouts.py, astrocut/tests/test_asdf_cut.py, astrocut/tests/test_make_cube.py
If an s3 URI is passed in as the `input_file` parameter to the `asdf_cut` function, open the resource with `s3fs` and use its http URL in `asdf.open()`.
This prevents users from having to open the resource themselves before passing the file into the `asdf_cut` function.
=> Handle an s3 URI in asdf_cut()

CHANGES.rst, astrocut/asdf_cutouts.py, astrocut/tests/test_asdf_cut.py, setup.cfg
`asdf_cut()` function now accepts `pathlib.Path` and `s3path.S3Path` obects as the `input_file` parameter.
Didn't require too many changes since `asdf.open()` already supports `pathlib` objects. For `s3path`, I added a second condition to run the `get_cloud_http` function.
=> Support for pathlib.Path and s3path.S3Path objects in asdf_cut()

.github/workflows/ci_workflows.yml, astrocut/utils/wcs_fitting.py, docs/astrocut/index.rst, tox.ini
Adds another testing environment that uses NumPy 2.0.0.
=> Asb 26944 numpy 2

astrocut/asdf_cutouts.py, astrocut/tests/test_asdf_cut.py
Modified the `_get_cloud_http` method to catch a `PermissionError`. If caught, this indicates that the user is trying to access a private resource, as we do in the Astrocut notebook on the Roman Science Platform. If that is the case, then the `S3FileSystem` is initialized with the `anon` parameter set to `False`.
=> Bugfix for Opening Files from the Cloud

astrocut/asdf_cutouts.py, astrocut/tests/test_asdf_cut.py
Added parameters to `asdf_cut` that allow the user to provide an S3 access key (`key`), secret access key (`secret`), or security token (`token`). These should only have an impact for private S3 buckets (`is_anon = False`), so I left in the logic to determine if a bucket is public or private.
=> Add parameters for S3 credentials

astrocut/asdf_cutouts.py, docs/astrocut/index.rst
Add documentation to warn users about cutout center accuracy when using an odd vs. even cutout size in `asdf_cut`. I added a note to the `cutout_size` parameter in the function docstring and updated the RST file with a warning block. I also changed the default cutout size for the function to be an odd number, and updated the docs to use odd sizes as well.
=> Documentation about odd vs. even cutout size in asdf_cut

astrocut/cutouts.py
Accessing the `.data` attribute on a compressed image causes the entire image to be decompressed and read into memory.  That defeats the ability of astrocut to reduce the IO requirements by reading only the necessary data.
Another benefit of the change is that it greatly reduces the memory requirements for the returned cutout.  The current version using the data section returns a subset of the full image array, which winds up dragging the entire array along with it.  The `.section` approach does not include the entire array.
This change instead uses the `.section` attribute to access the data, both when reading the pixels and when checking to see which extensions have images. The only remaining use of the `.data` attribute is for access to the cutout pixels. The implementation of the …
=> Improve speed by using .section attribute rather than .data attribute

.github/workflows/ci_workflows.yml
Adding a cron job to CI workflows so that our test suite runs everyday at 2 AM EST. This will run our test suite more regularly so that we can identify issues faster.
=> Add cron job to CI workflow

astrocut/cutouts.py, astrocut/tests/test_cutouts.py
Modified unit tests after discovery of bug in #132. Now, tests check that no files are written if the `memory_only` flag is set to `True` for both a single output file and multiple output files.
Also, only makes a new directory for output if `memory_only` is `False`.
=> Better tests for writing to memory only

.github/dependabot.yml, .github/workflows/ci_workflows.yml, .github/workflows/pypi-package.yml
As recommended by https://scientific-python.org/specs/spec-0008/#pin-github-actions-release-workflows-to-their-full-release-commit-shas , this PR changes your Actions workflow version pins to hashes, and updates to latest release hashes (at the time of writing) if needed.
This is an automated update made by the `batchpr` tool :robot: - feel free to close if it doesn't look good! You can report issues to @pllim.
[:ghost:](https://github.com/pllim/playpen/issues/60)
=> MNT: Use hash for Action workflow versions and update if needed

astrocut/Cutout.py, astrocut/FITSCutout.py, astrocut/ImageCutout.py, astrocut/cutouts.py, astrocut/tests/test_FITSCutout.py, astrocut/tests/test_ImageCutout.py, astrocut/tests/test_cutouts.py
This PR implements the generalized architecture for creating cutouts from FITS files. It implements `Cutout`, `ImageCutout`, and `FITSCutout`. It also changes the functions in `cutouts.py` to call the aforementioned classes and updates the test suite with a new file, `test_FITSCutout.py`.
Here is a class diagram of the new generalized architecture, though it may not be fully updated: https://innerspace.stsci.edu/display/MASTC/Class+Diagram
Considerations:
- While implementing this new generalized architecture, I'm focusing on restructuring the code rather than adding features or making significant changes. The existing API should have no breaking changes, for now.
- Ideally, `FITSCutout` will eventually use the `_get_cutout_data` method defined in `ImageCutout` that uses …
=> Generalization classes for FITS cutouts

.github/workflows/ci_workflows.yml, tox.ini
This PR updates the tox and github workflow configuration files to run tests with 3.11 3.12 and 3.13.
=> add 3.11 3.12 and 3.13 to CI

.github/workflows/ci_workflows.yml
Update our CI workflow to use a codecov upload token.
Successful run is here: https://github.com/spacetelescope/astrocut/actions/runs/14980614049/job/42134176448?pr=156
=> Update CI workflow to use codecov token

astrocut/asdf_cutout.py, astrocut/tests/test_asdf_cutout.py
Addresses #159 
I also noticed that `array_shape` and `pixel_shape` for the GWCS object were incorrect, so I fixed those as well and added a test case.
=> Bugfix for flipped axes in GWCS bounding box

CHANGES.rst, astrocut/cutout.py, astrocut/footprint_cutout.py, astrocut/tests/test_tess_footprint_cutout.py
Added support in `ra_dec_crossmatch` for a cutout size of zero, enabling single-point matching to FFIs that contain the specified coordinates. This single-point matching is significantly faster than computing an intersection between polygons.
If only one axis of the cutout size is equal to zero, I add a negligible amount in that dimension and treat the cutout as a very thin rectangle.
=> Coordinate footprint crossmatch with a cutout size of 0
